name: Build-and-push-to-ecr
on: [push]

jobs: 
    build-and-push:
        runs-on: ubuntu-latest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3
        -   name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: "us-east-2"
        -   name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
            with:
              mask-password: 'true'
        -   name: Build, tag, and push image to Amazon ECR
            id: build-image
            env:
              ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
              ECR_REPOSITORY: chatty_npc
              IMAGE_TAG: ${{ github.sha }}
            run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
              docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
        -   name: Check for OpenAI
            run: |
              printenv | sed 's;=.*;;' | grep "OPENAI_API_KEY.*"